---
- name: configuration check
  hosts: all
  tasks:
    - name: project settings check (1/2)
      fail: msg="Make sure project_name and secret_key are correctly defined"
      when: project_name|default('') == '' or secret_key|default('') == ''

    - name: project settings check (2/2)
      fail: msg="Make sure the project is either created or the repo pulled"
      when: not (pull_repo and repo_url) and not create_project


# Development Machines
- name: configure and deploy the development environment
  sudo: yes
  hosts: vagrant
  gather_facts: no
  roles:
    - dbserver
    - gunicorn
    - nginx
    - development
    - testing
