# Repository settings
repo_version: "master"

# General Sjango Settings
django_manage_path: "{{ code_dir }}/{{ project_name }}"

secret_key: ""
django_enable_debug: True

django_log_directory: "{{ log_dir }}/django"

# Django Database Settings
settings_dbname: "{{ project_name }}"
settings_dbuser: "{{ project_name }}"
settings_dbpassword: "{{ project_name }}"
settings_dbbackend: postgresql_psycopg2
settings_dbhost: localhost
settings_dbport: 5432

django_settings_base: settings
django_settings_path: "{{ code_dir }}/{{ project_name }}/{{ project_name }}/{{ django_settings_base }}.py"
django_settings_python_path: "{{ project_name }}.{{ django_settings_base }}"
django_settings_template_name: "{{ django_settings_base }}.py.j2"
